# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'thematic_map_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ThematicMapDialog(object):
    def setupUi(self, ThematicMapDialog):
        ThematicMapDialog.setObjectName("ThematicMapDialog")
        ThematicMapDialog.resize(550, 750)
        self.verticalLayout = QtWidgets.QVBoxLayout(ThematicMapDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        
        # Scroll area for all controls
        self.scrollArea = QtWidgets.QScrollArea(ThematicMapDialog)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollWidget = QtWidgets.QWidget()
        self.scrollLayout = QtWidgets.QVBoxLayout(self.scrollWidget)
        
        # ===== LAYER & FIELD GROUP =====
        self.groupBox = QtWidgets.QGroupBox(self.scrollWidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.layerCombo = QtWidgets.QComboBox(self.groupBox)
        self.layerCombo.setObjectName("layerCombo")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.layerCombo)
        
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.fieldCombo = QtWidgets.QComboBox(self.groupBox)
        self.fieldCombo.setObjectName("fieldCombo")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.fieldCombo)
        
        self.verticalLayout_2.addLayout(self.formLayout)
        self.scrollLayout.addWidget(self.groupBox)
        
        # ===== CLASSIFICATION METHOD GROUP =====
        self.classMethodGroup = QtWidgets.QGroupBox(self.scrollWidget)
        self.classMethodGroup.setObjectName("classMethodGroup")
        self.classMethodLayout = QtWidgets.QFormLayout(self.classMethodGroup)
        
        self.label_classmethod = QtWidgets.QLabel(self.classMethodGroup)
        self.label_classmethod.setObjectName("label_classmethod")
        self.classMethodLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_classmethod)
        
        self.classMethodCombo = QtWidgets.QComboBox(self.classMethodGroup)
        self.classMethodCombo.setObjectName("classMethodCombo")
        self.classMethodCombo.addItems(['Equal Intervals', 'Quantiles', 'Natural Breaks (Jenks)', 'Pretty Breaks', 'Standard Deviation'])
        self.classMethodLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.classMethodCombo)
        
        self.label_3 = QtWidgets.QLabel(self.classMethodGroup)
        self.label_3.setObjectName("label_3")
        self.classMethodLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.classSpinBox = QtWidgets.QSpinBox(self.classMethodGroup)
        self.classSpinBox.setMinimum(2)
        self.classSpinBox.setMaximum(15)
        self.classSpinBox.setProperty("value", 5)
        self.classSpinBox.setObjectName("classSpinBox")
        self.classMethodLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.classSpinBox)
        
        self.scrollLayout.addWidget(self.classMethodGroup)
        
        # ===== COLOR CUSTOMIZATION GROUP =====
        self.colorGroup = QtWidgets.QGroupBox(self.scrollWidget)
        self.colorGroup.setObjectName("colorGroup")
        self.colorLayout = QtWidgets.QFormLayout(self.colorGroup)
        
        self.label_4 = QtWidgets.QLabel(self.colorGroup)
        self.label_4.setObjectName("label_4")
        self.colorLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        
        self.colorCombo = QtWidgets.QComboBox(self.colorGroup)
        self.colorCombo.setObjectName("colorCombo")
        self.colorCombo.addItems(['Blue', 'Red', 'Green', 'Rainbow', 'Purple', 'Heat', 'Orange', 'Custom'])
        self.colorLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.colorCombo)
        
        self.reverseColorCheckBox = QtWidgets.QCheckBox(self.colorGroup)
        self.reverseColorCheckBox.setObjectName("reverseColorCheckBox")
        self.colorLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.reverseColorCheckBox)
        
        self.label_mincolor = QtWidgets.QLabel(self.colorGroup)
        self.label_mincolor.setObjectName("label_mincolor")
        self.colorLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_mincolor)
        
        self.minColorButton = QtWidgets.QPushButton(self.colorGroup)
        self.minColorButton.setObjectName("minColorButton")
        self.minColorButton.setMaximumWidth(100)
        self.minColorButton.setStyleSheet("background-color: #ADD8E6;")
        self.colorLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.minColorButton)
        
        self.label_maxcolor = QtWidgets.QLabel(self.colorGroup)
        self.label_maxcolor.setObjectName("label_maxcolor")
        self.colorLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_maxcolor)
        
        self.maxColorButton = QtWidgets.QPushButton(self.colorGroup)
        self.maxColorButton.setObjectName("maxColorButton")
        self.maxColorButton.setMaximumWidth(100)
        self.maxColorButton.setStyleSheet("background-color: #0851CC;")
        self.colorLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.maxColorButton)
        
        self.scrollLayout.addWidget(self.colorGroup)
        
        # ===== MAP STYLING GROUP =====
        self.styleGroup = QtWidgets.QGroupBox(self.scrollWidget)
        self.styleGroup.setObjectName("styleGroup")
        self.styleLayout = QtWidgets.QFormLayout(self.styleGroup)
        
        self.label_border = QtWidgets.QLabel(self.styleGroup)
        self.label_border.setObjectName("label_border")
        self.styleLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_border)
        
        self.borderColorButton = QtWidgets.QPushButton(self.styleGroup)
        self.borderColorButton.setObjectName("borderColorButton")
        self.borderColorButton.setMaximumWidth(100)
        self.borderColorButton.setStyleSheet("background-color: #323232;")
        self.styleLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.borderColorButton)
        
        self.label_borderwidth = QtWidgets.QLabel(self.styleGroup)
        self.label_borderwidth.setObjectName("label_borderwidth")
        self.styleLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_borderwidth)
        
        self.borderWidthSpinBox = QtWidgets.QDoubleSpinBox(self.styleGroup)
        self.borderWidthSpinBox.setMinimum(0.0)
        self.borderWidthSpinBox.setMaximum(5.0)
        self.borderWidthSpinBox.setSingleStep(0.1)
        self.borderWidthSpinBox.setProperty("value", 0.2)
        self.borderWidthSpinBox.setObjectName("borderWidthSpinBox")
        self.styleLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.borderWidthSpinBox)
        
        self.label_opacity = QtWidgets.QLabel(self.styleGroup)
        self.label_opacity.setObjectName("label_opacity")
        self.styleLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_opacity)
        
        self.opacitySlider = QtWidgets.QSlider(QtCore.Qt.Horizontal, self.styleGroup)
        self.opacitySlider.setMinimum(0)
        self.opacitySlider.setMaximum(100)
        self.opacitySlider.setProperty("value", 100)
        self.opacitySlider.setObjectName("opacitySlider")
        self.opacityLayout = QtWidgets.QHBoxLayout()
        self.opacityLayout.addWidget(self.opacitySlider)
        self.opacityLabel = QtWidgets.QLabel("100%", self.styleGroup)
        self.opacityLayout.addWidget(self.opacityLabel)
        self.styleLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.opacityLayout)
        
        self.labelCheckBox = QtWidgets.QCheckBox(self.styleGroup)
        self.labelCheckBox.setChecked(True)
        self.labelCheckBox.setObjectName("labelCheckBox")
        self.styleLayout.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.labelCheckBox)
        
        self.label_labelfield = QtWidgets.QLabel(self.styleGroup)
        self.label_labelfield.setObjectName("label_labelfield")
        self.styleLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_labelfield)
        
        self.labelFieldCombo = QtWidgets.QComboBox(self.styleGroup)
        self.labelFieldCombo.setObjectName("labelFieldCombo")
        self.styleLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.labelFieldCombo)
        
        self.label_fontsize = QtWidgets.QLabel(self.styleGroup)
        self.label_fontsize.setObjectName("label_fontsize")
        self.styleLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_fontsize)
        
        self.fontSizeSpinBox = QtWidgets.QSpinBox(self.styleGroup)
        self.fontSizeSpinBox.setMinimum(6)
        self.fontSizeSpinBox.setMaximum(32)
        self.fontSizeSpinBox.setProperty("value", 10)
        self.fontSizeSpinBox.setObjectName("fontSizeSpinBox")
        self.styleLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.fontSizeSpinBox)
        
        self.label_fontcolor = QtWidgets.QLabel(self.styleGroup)
        self.label_fontcolor.setObjectName("label_fontcolor")
        self.styleLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_fontcolor)
        
        self.fontColorButton = QtWidgets.QPushButton(self.styleGroup)
        self.fontColorButton.setObjectName("fontColorButton")
        self.fontColorButton.setMaximumWidth(100)
        self.fontColorButton.setStyleSheet("background-color: #000000;")
        self.styleLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.fontColorButton)
        
        self.label_bgcolor = QtWidgets.QLabel(self.styleGroup)
        self.label_bgcolor.setObjectName("label_bgcolor")
        self.styleLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_bgcolor)
        
        self.bgColorButton = QtWidgets.QPushButton(self.styleGroup)
        self.bgColorButton.setObjectName("bgColorButton")
        self.bgColorButton.setMaximumWidth(100)
        self.bgColorButton.setStyleSheet("background-color: #FFFFFF;")
        self.styleLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.bgColorButton)
        
        self.bgEnabledCheckBox = QtWidgets.QCheckBox(self.styleGroup)
        self.bgEnabledCheckBox.setText("Enable Background")
        self.bgEnabledCheckBox.setChecked(True)
        self.bgEnabledCheckBox.setObjectName("bgEnabledCheckBox")
        self.styleLayout.setWidget(8, QtWidgets.QFormLayout.SpanningRole, self.bgEnabledCheckBox)
        
        self.scrollLayout.addWidget(self.styleGroup)
        
        # ===== EXPORT & SAVE GROUP =====
        self.exportGroup = QtWidgets.QGroupBox(self.scrollWidget)
        self.exportGroup.setObjectName("exportGroup")
        self.exportLayout = QtWidgets.QVBoxLayout(self.exportGroup)
        
        self.saveStyleButton = QtWidgets.QPushButton(self.exportGroup)
        self.saveStyleButton.setObjectName("saveStyleButton")
        self.exportLayout.addWidget(self.saveStyleButton)
        
        self.loadStyleButton = QtWidgets.QPushButton(self.exportGroup)
        self.loadStyleButton.setObjectName("loadStyleButton")
        self.exportLayout.addWidget(self.loadStyleButton)
        
        self.exportQMLButton = QtWidgets.QPushButton(self.exportGroup)
        self.exportQMLButton.setObjectName("exportQMLButton")
        self.exportLayout.addWidget(self.exportQMLButton)
        
        self.scrollLayout.addWidget(self.exportGroup)
        
        # ===== STATISTICS GROUP =====
        self.statsGroup = QtWidgets.QGroupBox(self.scrollWidget)
        self.statsGroup.setObjectName("statsGroup")
        self.statsLayout = QtWidgets.QVBoxLayout(self.statsGroup)
        
        self.statsTextEdit = QtWidgets.QTextEdit(self.statsGroup)
        self.statsTextEdit.setReadOnly(True)
        self.statsTextEdit.setMaximumHeight(120)
        self.statsTextEdit.setObjectName("statsTextEdit")
        self.statsLayout.addWidget(self.statsTextEdit)
        
        self.generateLegendButton = QtWidgets.QPushButton(self.statsGroup)
        self.generateLegendButton.setObjectName("generateLegendButton")
        self.statsLayout.addWidget(self.generateLegendButton)
        
        self.scrollLayout.addWidget(self.statsGroup)
        
        # Add stretch to scrollable area
        self.scrollLayout.addStretch()
        self.scrollArea.setWidget(self.scrollWidget)
        self.verticalLayout.addWidget(self.scrollArea)
        
        # ===== BUTTON BOX =====
        self.buttonBox = QtWidgets.QDialogButtonBox(ThematicMapDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(ThematicMapDialog)
        self.buttonBox.accepted.connect(ThematicMapDialog.generateThematicMap)
        self.buttonBox.rejected.connect(ThematicMapDialog.close)
        QtCore.QMetaObject.connectSlotsByName(ThematicMapDialog)

    def retranslateUi(self, ThematicMapDialog):
        _translate = QtCore.QCoreApplication.translate
        ThematicMapDialog.setWindowTitle(_translate("ThematicMapDialog", "One Click Thematic Map v2.0"))
        self.groupBox.setTitle(_translate("ThematicMapDialog", "Layer & Field Selection"))
        self.label.setText(_translate("ThematicMapDialog", "Layer:"))
        self.label_2.setText(_translate("ThematicMapDialog", "Numeric Field:"))
        
        self.classMethodGroup.setTitle(_translate("ThematicMapDialog", "Classification Method"))
        self.label_classmethod.setText(_translate("ThematicMapDialog", "Method:"))
        self.label_3.setText(_translate("ThematicMapDialog", "Classes:"))
        
        self.colorGroup.setTitle(_translate("ThematicMapDialog", "Color Customization"))
        self.label_4.setText(_translate("ThematicMapDialog", "Color Scheme:"))
        self.reverseColorCheckBox.setText(_translate("ThematicMapDialog", "Reverse Colors"))
        self.label_mincolor.setText(_translate("ThematicMapDialog", "Min Color:"))
        self.minColorButton.setText(_translate("ThematicMapDialog", "Choose"))
        self.label_maxcolor.setText(_translate("ThematicMapDialog", "Max Color:"))
        self.maxColorButton.setText(_translate("ThematicMapDialog", "Choose"))
        
        self.styleGroup.setTitle(_translate("ThematicMapDialog", "Map Styling"))
        self.label_border.setText(_translate("ThematicMapDialog", "Border Color:"))
        self.borderColorButton.setText(_translate("ThematicMapDialog", "Choose"))
        self.label_borderwidth.setText(_translate("ThematicMapDialog", "Border Width:"))
        self.label_opacity.setText(_translate("ThematicMapDialog", "Opacity:"))
        self.labelCheckBox.setText(_translate("ThematicMapDialog", "Show Labels"))
        
        self.exportGroup.setTitle(_translate("ThematicMapDialog", "Export & Save"))
        self.saveStyleButton.setText(_translate("ThematicMapDialog", "Save Current Style"))
        self.loadStyleButton.setText(_translate("ThematicMapDialog", "Load Saved Style"))
        self.exportQMLButton.setText(_translate("ThematicMapDialog", "Export as QML"))
        
        self.statsGroup.setTitle(_translate("ThematicMapDialog", "Statistics & Legend"))
        self.generateLegendButton.setText(_translate("ThematicMapDialog", "Generate Legend on Map"))
        
        self.label_labelfield.setText(_translate("ThematicMapDialog", "Label Field:"))
        self.label_fontsize.setText(_translate("ThematicMapDialog", "Font Size:"))
        self.label_fontcolor.setText(_translate("ThematicMapDialog", "Font Color:"))
        self.fontColorButton.setText(_translate("ThematicMapDialog", "Choose"))
        self.label_bgcolor.setText(_translate("ThematicMapDialog", "Background Color:"))
        self.bgColorButton.setText(_translate("ThematicMapDialog", "Choose"))
